gb28181:
  transport: "UDP" # 信令默认使用UDP 也可以TCP
  platform:
    domain: "34020000002" # 平台域
    id: "34020000002000000001" # 平台ID
    password: "123456" # 平台密码
    ip: "127.0.0.1" # 平台IP
    port: 15060 # 平台端口

  device:
    id: "34020000001320000330" # 设备ID
    # 实际不会用到设备的IP和端口 只是sip传输过去
    ip: "127.0.0.1" # 设备IP
    port: 5060 # 设备端口

jt1078:
  # 只支持点播 使用TCP被动模式 即设备TCP链接到gb28181平台
  # 音视频请求的jt1078文件 jt1078转ps流
  # "../testdata/data.txt" jt1078的h264文件
  # "../testdata/audio_data.txt" jt1078的h264+g711a文件
  file: "../testdata/audio_data.txt"