name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build
        run: |
          cd ./example/web/service
          go build -o service || exit 1
          cd ../notice
          go build -o notice || exit 1
          cd ../alarm
          go build -o alarm || exit 1
          cd ../../../

      - name: releases
        run: |
          mkdir -p web/service
          cp -r ./example/web/testdata/ web/testdata
          cp ./example/web/README.md web/README.md
          cp ./example/web/service/service web/service/
          cp ./example/web/service/config.yaml web/service/
          mkdir -p web/notice
          cp ./example/web/notice/notice web/notice/
          mkdir -p web/alarm
          cp ./example/web/alarm/alarm web/alarm/
          cp ./example/web/alarm/config.yaml web/alarm/         
          zip -r web-linux.zip web
